export enum RouterPathName {
    Home = '/',
    AboutUs = '/about-us',
    ContactUs = '/contact-us',
    HowItWorks = '/how-it-works',
    Courses = '/courses',
    NotFound = '/404',
    ThankYou = '/thank-you',
    NoPayment = '/thank-you-no-payment',
    Contact = '/contact',
    Login = '/login',
    UnprotectedLogin = '/login-unprotected',
    Register = '/register',
    CompleteAccountSetup = '/complete-account-setup',
    Teacher = '/teacher/:teacherName',
    Teachers = '/teachers',
    Classes = '/classes',
    Blogs = '/blogs',
    Profile = '/profile'
}
